const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const state={unlocked:+localStorage.egyptUnlocked||0,game:null,step:0,mistakes:0,sound:true,volume:.45,phase:0,code:[],memory:[],questions:[],lastMove:null,captured:false,found:[],huntOrder:[]};
const huntItems=[{id:'crown',icon:7,label:'CROWN',clue:'Find something a Pharaoh can wear.'},{id:'scroll',icon:8,label:'PAPYRUS',clue:'Find something you can read.'},{id:'key',icon:9,label:'KEY',clue:'Find something that opens a locked door.'},{id:'jewel',icon:10,label:'JEWEL',clue:'Find the precious blue stone.'},{id:'chest',icon:2,label:'CHEST',clue:'Find something that holds treasure.'}];
const shuffle=list=>{const copy=[...list];for(let i=copy.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[copy[i],copy[j]]=[copy[j],copy[i]]}return copy};
const games={
 desert:{title:'DESERT DASH',kicker:'JOURNEY TO THE PYRAMID',questions:[['The camel is ___ the pyramid.','behind',['under','behind','between']],['Choose the opposite of HOT.','cold',['old','cold','small']],['I ___ a treasure map.','have',['has','have','am']],['The oasis is ___ two dunes.','between',['on','between','behind']],['Choose the animal.','camel',['pyramid','camel','water']],['We ___ near the pyramid.','are',['is','are','has']]]},
 tomb:{title:"MUMMY'S TOMB",kicker:'ESCAPE FROM THE TOMB',questions:[['How many snakes can you see? 🐍 🐍 🐍','three',['two','three','four']],['Choose the correct sentence.','The mummy has a key.',['The mummy have a key.','The mummy has a key.','The mummy having a key.']],['The torches ___ bright.','are',['is','are','has']],['Choose the plural of DOOR.','doors',['doores','doors','doories']],['The key is ___ the box.','in',['at','in','between']],['We ___ from the mummy.','run',['runs','run','running']]]}
};
let sfxContext;
function getSfxContext(){sfxContext=sfxContext||new AudioContext();if(sfxContext.state==='suspended')sfxContext.resume();return sfxContext}
function sfxTone(ctx,frequency,start,duration,volume,type='sine'){const oscillator=ctx.createOscillator(),gain=ctx.createGain(),filter=ctx.createBiquadFilter();oscillator.type=type;oscillator.frequency.setValueAtTime(frequency,start);filter.type='lowpass';filter.frequency.value=2400;gain.gain.setValueAtTime(.0001,start);gain.gain.exponentialRampToValueAtTime(volume*state.volume/.45,start+.018);gain.gain.exponentialRampToValueAtTime(.0001,start+duration);oscillator.connect(filter);filter.connect(gain);gain.connect(ctx.destination);oscillator.start(start);oscillator.stop(start+duration+.03)}
function correctSound(){if(!state.sound)return;duckBackground(900);const ctx=getSfxContext(),now=ctx.currentTime+.015;[659.25,830.61,987.77,1318.51].forEach((note,i)=>{sfxTone(ctx,note,now+i*.075,.34-i*.025,.055-i*.006,i===3?'sine':'triangle');sfxTone(ctx,note*2,now+i*.075,.18,.012,'sine')})}
function forbiddenSound(){if(!state.sound)return;duckBackground(750);const ctx=getSfxContext(),now=ctx.currentTime+.01;[0,.19].forEach((delay,i)=>{const oscillator=ctx.createOscillator(),gain=ctx.createGain(),filter=ctx.createBiquadFilter();oscillator.type='sawtooth';oscillator.frequency.setValueAtTime(i?138:174,now+delay);oscillator.frequency.exponentialRampToValueAtTime(i?82:104,now+delay+.2);filter.type='lowpass';filter.frequency.value=520;gain.gain.setValueAtTime(.0001,now+delay);gain.gain.exponentialRampToValueAtTime(.055*state.volume/.45,now+delay+.025);gain.gain.exponentialRampToValueAtTime(.0001,now+delay+.22);oscillator.connect(filter);filter.connect(gain);gain.connect(ctx.destination);oscillator.start(now+delay);oscillator.stop(now+delay+.24)})}
function beep(ok=true){duckBackground(ok?900:750);ok?correctSound():forbiddenSound()}
const audioTracks={home:'assets/sounds/showcase.mp3',desert:'assets/sounds/desert.mp3',tomb:'assets/sounds/tomb.mp3',treasure:'assets/sounds/treasure.mp3'};
const backgroundAudio=new Audio();backgroundAudio.loop=true;backgroundAudio.preload='auto';
const mummyGrowl=new Audio('assets/sounds/mummy-growl.mp3');mummyGrowl.preload='auto';
let activeTrack='home';
const BGM_RATIO=.3;
const HOME_BGM_RATIO=.21;
let duckTimer;
function setBackgroundLevel(ratio=activeTrack==='home'?HOME_BGM_RATIO:BGM_RATIO){backgroundAudio.volume=Math.min(1,state.volume*ratio)}
function duckBackground(duration=950){if(!state.sound)return;clearTimeout(duckTimer);setBackgroundLevel(.08);duckTimer=setTimeout(()=>setBackgroundLevel(),duration)}
function playBackground(name='home'){activeTrack=name;const source=audioTracks[name];if(!source)return;if(!backgroundAudio.src.endsWith(source.replaceAll('/','/'))){backgroundAudio.src=source;backgroundAudio.load()}setBackgroundLevel();if(state.sound)backgroundAudio.play().catch(()=>{})}
function playMummyGrowl(){if(!state.sound)return;duckBackground(1400);mummyGrowl.currentTime=0;mummyGrowl.volume=Math.min(1,state.volume*1.25);mummyGrowl.play().catch(()=>{})}
function syncAudioUI(){document.body.classList.toggle('audio-muted',!state.sound);$$('input[type="range"]').filter(i=>i.closest('.volume-slider')).forEach(i=>i.value=Math.round(state.volume*100))}
function toggleAudio(){state.sound=!state.sound;if(state.sound)playBackground(activeTrack);else{backgroundAudio.pause();mummyGrowl.pause()}syncAudioUI()}
function setAudioVolume(value){state.volume=Math.max(0,Math.min(1,+value/100));setBackgroundLevel();mummyGrowl.volume=Math.min(1,state.volume*1.25);if(state.volume===0&&state.sound)toggleAudio();else if(state.volume>0&&!state.sound)toggleAudio();syncAudioUI()}
window.addEventListener('load',()=>{syncAudioUI();playBackground('home');document.addEventListener('pointerdown',()=>{if(state.sound&&backgroundAudio.paused)backgroundAudio.play().catch(()=>{})},{once:true,capture:true})});
function triggerSandstorm(){const scene=$('#scene');scene.classList.remove('storm-hit');void scene.offsetWidth;scene.classList.add('storm-hit');const storm=document.createElement('div');storm.className='sandstorm';storm.innerHTML=`<div class="storm-cloud"></div><div class="storm-warning"><b>!</b><span>WRONG WAY</span><small>Try another answer</small></div>${Array.from({length:30},(_,i)=>`<i style="--i:${i};--y:${(i*29)%100}%"></i>`).join('')}`;scene.appendChild(storm);setTimeout(()=>{storm.remove();scene.classList.remove('storm-hit')},1450)}
function toast(t){const el=$('#toast');el.textContent=t;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),1300)}
function renderProgress(){state.unlocked=+localStorage.egyptUnlocked||0;const complete=state.unlocked===3;$('.live-progress').classList.toggle('chest-complete',complete);$('#scarabs').innerHTML=[0,1,2].map(i=>`<canvas class="scarab-dot ${i<state.unlocked?'earned':'silhouette'}" data-reward="${i}" aria-label="${i<state.unlocked?'Golden':'Missing'} Scarab ${i+1}"></canvas>`).join('');if(window.rewardAtlas){$$('#scarabs canvas').forEach(c=>drawReward(c,+c.dataset.reward,c.classList.contains('silhouette')));const master=$('.master-scarab');if(master)drawReward(master,2,false)}if(window.chestAsset)drawChest($('#expeditionChest'),complete?1:0);$$('.hotspot').forEach((c,i)=>{const locked=i>state.unlocked;c.classList.toggle('locked',locked);c.querySelector('span').textContent=locked?'':'PLAY';c.setAttribute('aria-label',locked?'Game locked':`Play ${c.dataset.game}`)})}
function loadAtlas(){const img=new Image();img.src='assets/egypt-icons-source.png';img.onload=()=>{window.atlas=img;$$('.atlas-icon').forEach(c=>drawIcon(c,+c.dataset.icon,img))};loadRewardAtlas();loadChest();loadCamel();loadChase();loadSnake()}
function drawIcon(c,index,img=window.atlas){if(!img)return;c.width=240;c.height=240;const x=index%4,y=Math.floor(index/4),sw=img.width/4,sh=img.height/3,ctx=c.getContext('2d');ctx.clearRect(0,0,240,240);ctx.drawImage(img,x*sw,y*sh,sw,sh,0,0,240,240);const d=ctx.getImageData(0,0,240,240);for(let i=0;i<d.data.length;i+=4){const r=d.data[i],g=d.data[i+1],b=d.data[i+2];if(r>190&&b>150&&g<80)d.data[i+3]=Math.max(0,255-(Math.min(r,b)-Math.max(g,20))*3)}ctx.putImageData(d,0,0)}
function loadRewardAtlas(){const img=new Image();img.src='assets/golden-scarabs.png';img.onload=()=>{window.rewardAtlas=img;$$('#scarabs canvas').forEach(c=>drawReward(c,+c.dataset.reward,c.classList.contains('silhouette')));const win=$('#winScarab');if(win)drawReward(win,+win.dataset.reward,false);const master=$('.master-scarab');if(master)drawReward(master,2,false)}}
function removeRewardBackground(ctx,size){const image=ctx.getImageData(0,0,size,size),pixels=image.data,seen=new Uint8Array(size*size),queue=[],isKey=(p,soft=false)=>{const i=p*4,r=pixels[i],g=pixels[i+1],b=pixels[i+2];return soft?r>115&&b>70&&r>g*1.12&&b>g*.88:r>145&&b>100&&g<145&&r>g*1.22&&b>g};const add=p=>{if(p>=0&&p<seen.length&&!seen[p]&&isKey(p)){seen[p]=1;queue.push(p)}};for(let x=0;x<size;x++){add(x);add((size-1)*size+x)}for(let y=0;y<size;y++){add(y*size);add(y*size+size-1)}for(let head=0;head<queue.length;head++){const p=queue[head],x=p%size;if(x)add(p-1);if(x<size-1)add(p+1);if(p>=size)add(p-size);if(p<size*(size-1))add(p+size)}for(let pass=0;pass<2;pass++){const edge=[];for(let p=0;p<seen.length;p++)if(!seen[p]&&isKey(p,true)){const x=p%size;if((x&&seen[p-1])||(x<size-1&&seen[p+1])||(p>=size&&seen[p-size])||(p<size*(size-1)&&seen[p+size]))edge.push(p)}edge.forEach(p=>seen[p]=1)}for(let p=0;p<seen.length;p++)if(seen[p])pixels[p*4+3]=0;ctx.putImageData(image,0,0)}
function drawReward(c,index,silhouette=false){const img=window.rewardAtlas;if(!img)return;c.width=256;c.height=256;const ctx=c.getContext('2d'),cell=img.width/3,crop=Math.min(cell,img.height),sy=(img.height-crop)/2;ctx.clearRect(0,0,256,256);ctx.drawImage(img,index*cell,sy,cell,crop,0,0,256,256);removeRewardBackground(ctx,256)}
function loadChest(){const img=new Image();img.src='assets/expedition-chest-inlay.png';img.onload=()=>{window.chestAsset=img;drawChest($('#expeditionChest'),state.unlocked===3)}}
function drawChest(c,index){if(!c||!window.chestAsset)return;const img=window.chestAsset,cell=img.width/2,ctx=c.getContext('2d');if(index===0){c.width=640;c.height=460;ctx.clearRect(0,0,640,460);ctx.drawImage(img,70,270,750,585,0,0,640,460)}else{c.width=600;c.height=600;ctx.clearRect(0,0,600,600);ctx.drawImage(img,cell+45,0,cell-225,img.height,0,0,600,600)}const d=ctx.getImageData(0,0,c.width,c.height);for(let i=0;i<d.data.length;i+=4){const r=d.data[i],g=d.data[i+1],b=d.data[i+2];if(r>185&&b>145&&g<105)d.data[i+3]=Math.max(0,255-(Math.min(r,b)-Math.max(g,20))*3)}ctx.putImageData(d,0,0)}
function loadCamel(){const img=new Image();img.src='assets/desert-camel.png';img.onload=()=>{window.camelAsset=img;const c=$('#camelRunner');if(c)drawCamel(c)}}
function drawCamel(c){const img=window.camelAsset;if(!img)return;c.width=300;c.height=300;const ctx=c.getContext('2d');ctx.drawImage(img,0,0,300,300);const d=ctx.getImageData(0,0,300,300);for(let i=0;i<d.data.length;i+=4){const r=d.data[i],g=d.data[i+1],b=d.data[i+2];if(r>185&&b>145&&g<105)d.data[i+3]=Math.max(0,255-(Math.min(r,b)-Math.max(g,20))*3)}ctx.putImageData(d,0,0)}
function loadChase(){const img=new Image();img.src='assets/tomb-chase.png';img.onload=()=>{window.chaseAsset=img;$$('.chase-character canvas').forEach(c=>drawChase(c,+c.dataset.character))}}
function drawChase(c,index){const img=window.chaseAsset;if(!img)return;c.width=300;c.height=300;const ctx=c.getContext('2d'),cell=img.width/2,crop=Math.min(cell,img.height),sy=(img.height-crop)/2;ctx.drawImage(img,index*cell,sy,cell,crop,0,0,300,300);const d=ctx.getImageData(0,0,300,300);for(let i=0;i<d.data.length;i+=4){const r=d.data[i],g=d.data[i+1],b=d.data[i+2];if(r>185&&b>145&&g<105)d.data[i+3]=Math.max(0,255-(Math.min(r,b)-Math.max(g,20))*3)}ctx.putImageData(d,0,0)}
function loadSnake(){const img=new Image();img.src='assets/golden-snake.png';img.onload=()=>{window.snakeAsset=img;$$('.question-snake').forEach(drawSnake)}}
function drawSnake(c){const img=window.snakeAsset;if(!img)return;c.width=220;c.height=220;const ctx=c.getContext('2d');ctx.drawImage(img,0,0,220,220);const d=ctx.getImageData(0,0,220,220);for(let i=0;i<d.data.length;i+=4){const r=d.data[i],g=d.data[i+1],b=d.data[i+2],min=Math.min(r,g,b);if(min>238)d.data[i+3]=Math.max(0,255-(min-238)*16)}ctx.putImageData(d,0,0)}
function openGame(key){const idx=['desert','tomb','treasure'].indexOf(key);if(idx>state.unlocked){toast('Earn the previous scarab first!');beep(false);return}state.game=key;state.step=0;state.mistakes=0;state.phase=0;state.code=[];state.lastMove=null;state.captured=false;state.found=[];state.huntOrder=shuffle(huntItems);state.questions=games[key]?shuffle(games[key].questions).map(q=>[q[0],q[1],shuffle(q[2])]):[];$('#game').classList.remove('snake-question-mode','treasure-hunt-mode','tomb-game-mode');$('#game').classList.toggle('tomb-game-mode',key==='tomb');$('.home-nav').hidden=true;$('#home').classList.remove('active');$('#game').classList.add('active');const g=games[key]||{title:"PHARAOH'S TREASURE",kicker:'THE FINAL CHAMBER'};$('#gameTitle').textContent=g.title;$('#gameKicker').textContent=g.kicker;playBackground(key);renderGame()}
function renderGame(){if(state.game==='desert')renderDesert();else if(state.game==='tomb')renderTomb();else renderTreasure()}
function questionUI(q){const snakes=q[0].includes('🐍');$('#game').classList.toggle('snake-question-mode',snakes);$('#challenge').classList.toggle('snake-challenge',snakes);const question=`<p class="question">${snakes?q[0].replace(/🐍/g,'').trim():q[0]}</p>`;const snakeCount='<div class="snake-count" aria-label="three snakes"><canvas class="question-snake"></canvas><canvas class="question-snake"></canvas><canvas class="question-snake"></canvas></div>';$('#challenge').innerHTML=`${snakes?`<div class="snake-question-line">${question}${snakeCount}</div>`:question}<div class="answers">${q[2].map(a=>`<button class="answer" data-answer="${a}">${a}</button>`).join('')}</div>`;if(snakes&&window.snakeAsset)$$('.question-snake').forEach(drawSnake);$$('.answer').forEach(b=>b.onclick=()=>answer(b.dataset.answer,q[1]))}
function answer(value,correct){if(state.captured)return;if(value===correct){beep();toast('BRILLIANT! ✨');state.lastMove=state.game==='tomb'?'boy':null;state.step++;setTimeout(()=>state.step>=6?win():renderGame(),500)}else{state.mistakes++;if(state.game==='desert'){forbiddenSound();triggerSandstorm();toast('SANDSTORM! CHOOSE ANOTHER PATH')}else{state.lastMove='mummy';playMummyGrowl();beep(false);toast('GRRRR... THE MUMMY IS CLOSER!');renderGame();if(state.mistakes>=6)setTimeout(triggerCapture,850)}}}
function triggerCapture(){if(state.game!=='tomb')return;state.captured=true;const scene=$('#scene');scene.classList.add('capture-scene');const trap=document.createElement('div');trap.className='capture-overlay';trap.innerHTML='<div class="capture-flash"></div><div class="sarcophagus"><div class="sarcophagus-lid"><b>𓂀</b><i>☥</i></div></div><strong>THE MUMMY GOT YOU!</strong><small>The ancient spell sends you back. Try again!</small>';scene.appendChild(trap);forbiddenSound();setTimeout(()=>{state.mistakes=0;state.lastMove=null;state.captured=false;renderTomb()},3600)}
function renderDesert(){const spots=[[38,73,1],[49,63,.88],[53,54,.76],[50,47,.66],[47,41,.57],[49,36,.49]],now=spots[Math.min(state.step,5)],prev=spots[Math.max(0,state.step-1)];$('#scene').className='scene desert-scene';$('#roomCount').innerHTML=`<small>SCARAB QUEST</small><strong>${state.step}<b>/6</b></strong>`;$('#scene').innerHTML=`<div class="scene-art"></div><div class="sun-rays"></div><div class="desert-dust">${Array.from({length:18},(_,i)=>`<i style="--i:${i};left:${(i*37)%100}%;bottom:${(i*17)%55}%;animation-duration:${4+i*.18}s"></i>`).join('')}</div><div class="mission-tag"><span>◆</span><div><small>CURRENT MISSION</small><b>Reach the Golden Pyramid</b></div></div><div class="stone-markers">${spots.map((p,i)=>`<i class="${i<state.step?'done':i===state.step?'current':''}" style="--x:${p[0]}%;--y:${p[1]}%;--s:${p[2]}">${i+1}</i>`).join('')}</div><div class="camel-runner" style="--x:${now[0]}%;--y:${now[1]}%;--s:${now[2]};--px:${prev[0]}%;--py:${prev[1]}%;--ps:${prev[2]}"><canvas id="camelRunner"></canvas><span></span></div>`;if(window.camelAsset)drawCamel($('#camelRunner'));questionUI(state.questions[state.step])}
function renderTomb(){const boyX=52+state.step*4.7,boyPrev=52+Math.max(0,state.step-1)*4.7,mummyX=Math.min(49,18+state.mistakes*5.2),mummyPrev=Math.min(49,18+Math.max(0,state.mistakes-1)*5.2);$('#scene').className='scene tomb-scene';$('#roomCount').innerHTML=`<small>ESCAPE ROUTE</small><strong>${state.step}<b>/6</b></strong>`;$('#scene').innerHTML=`<div class="scene-art"></div><div class="chase-floor"></div><div class="chase-character mummy-chaser ${state.lastMove==='mummy'?'moving':''}" style="--x:${mummyX}%;--px:${mummyPrev}%"><canvas data-character="1"></canvas><span></span></div><div class="chase-character boy-runner ${state.lastMove==='boy'?'moving':''}" style="--x:${boyX}%;--px:${boyPrev}%"><canvas data-character="0"></canvas><span></span></div><div class="chase-status"><b>ESCAPE!</b><div><i style="width:${Math.max(15,boyX-mummyX+30)}%"></i></div><small>${Math.round(boyX-mummyX)}m AHEAD</small></div>`;if(window.chaseAsset)$$('.chase-character canvas').forEach(c=>drawChase(c,+c.dataset.character));state.lastMove=null;questionUI(state.questions[state.step])}
const treasureTasks=[{q:'Find something you can wear.',answer:7,items:[7,8,9,10]},{q:'Find something you can read.',answer:8,items:[4,8,10,3]},{q:'Complete the word: C _ M E L',answer:'A',letters:['O','A','U']},{q:'Remember and match the symbols.',memory:true}];
function renderTreasure(){if(state.phase>=4){renderCode();return}$('#roomCount').textContent=`CLUE ${state.phase+1}/4`;$('#scene').className='scene treasure-room';const t=treasureTasks[state.phase];if(t.memory){renderMemory();return}$('#scene').innerHTML=`<div class="objects">${t.items?t.items.map(i=>`<button class="object" data-v="${i}"><canvas data-icon="${i}"></canvas></button>`).join(''):t.letters.map(l=>`<button class="object" data-v="${l}">${l}</button>`).join('')}</div>`;if(t.items)$$('.object canvas').forEach(c=>drawIcon(c,+c.dataset.icon));$('#challenge').innerHTML=`<p class="question">${t.q}</p><div class="code-slots">${['☀','🐍','👁','🪲'].slice(0,state.phase).join(' ')}</div>`;$$('.object').forEach(b=>b.onclick=()=>{if(String(b.dataset.v)===String(t.answer)){beep();state.code.push(['☀','🐍','👁'][state.phase]);state.phase++;toast('ANCIENT SYMBOL FOUND!');setTimeout(renderTreasure,500)}else{beep(false);toast('THE STONE RUMBLES... TRY AGAIN!')}})}
function renderTreasure(){const current=state.huntOrder[state.found.length];$('#game').classList.add('treasure-hunt-mode');$('#roomCount').innerHTML=`<small>TREASURE FOUND</small><strong>${state.found.length}<b>/5</b></strong>`;$('#scene').className='scene treasure-room hunt-room';$('#scene').innerHTML=`<button class="treasure-hotspot chest" data-item="chest" aria-label="Treasure chest"></button><button class="treasure-hotspot key" data-item="key" aria-label="Golden key"></button><button class="treasure-hotspot jewel" data-item="jewel" aria-label="Blue jewel"></button><button class="treasure-hotspot crown" data-item="crown" aria-label="Pharaoh crown"></button><button class="treasure-hotspot scroll" data-item="scroll" aria-label="Papyrus scroll"></button><div class="hunt-glimmer"></div>`;$('#challenge').className='challenge hunt-panel';$('#challenge').innerHTML=`<div class="hunt-copy"><small>OBJECT ${state.found.length+1} OF 5</small><p class="question">${current?current.clue:'Treasure collection complete!'}</p></div><div class="collection-tray">${huntItems.map(item=>{const found=state.found.includes(item.id);return `<div class="collection-slot ${found?'found':''}">${found?`<canvas data-icon="${item.icon}"></canvas>`:'<span>?</span>'}<small>${found?item.label:'HIDDEN'}</small></div>`}).join('')}</div>`;$$('.collection-slot canvas').forEach(c=>drawIcon(c,+c.dataset.icon));$$('.treasure-hotspot').forEach(b=>{b.classList.toggle('already-found',state.found.includes(b.dataset.item));b.onclick=()=>collectTreasure(b.dataset.item,b)})}
function collectTreasure(id,el){if(state.captured||state.found.includes(id))return;const target=state.huntOrder[state.found.length];if(id!==target.id){forbiddenSound();el.classList.remove('wrong');void el.offsetWidth;el.classList.add('wrong');toast('THAT IS NOT THE OBJECT — LOOK AGAIN!');return}state.captured=true;beep(true);el.classList.add('collecting');toast(`${target.label} FOUND!`);setTimeout(()=>{state.found.push(id);state.captured=false;if(state.found.length===huntItems.length){renderTreasure();setTimeout(win,900)}else renderTreasure()},850)}
function renderMemory(){const symbols=['☀','🐍','👁','🪲'];state.memory=[...symbols,...symbols].sort(()=>Math.random()-.5).map((v,i)=>({v,id:i,up:false,done:false}));drawMemory()}
function drawMemory(){const open=state.memory.filter(x=>x.up&&!x.done);$('#scene').innerHTML=`<div class="memory-grid">${state.memory.map(x=>`<button class="memory-card ${x.up?'flipped':''} ${x.done?'matched':''}" data-id="${x.id}">${x.up?x.v:'?'}</button>`).join('')}</div>`;$('#challenge').innerHTML='<p class="question">Find all matching hieroglyph pairs.</p>';$$('.memory-card').forEach(b=>b.onclick=()=>{const c=state.memory.find(x=>x.id==b.dataset.id);if(c.up||c.done||open.length===2)return;c.up=true;drawMemory();const now=state.memory.filter(x=>x.up&&!x.done);if(now.length===2)setTimeout(()=>{if(now[0].v===now[1].v){now.forEach(x=>x.done=true);beep()}else{now.forEach(x=>x.up=false);beep(false)}if(state.memory.every(x=>x.done)){state.code.push('🪲');state.phase++;toast('MEMORY SEAL BROKEN!');setTimeout(renderTreasure,600)}else drawMemory()},600)})}
function renderCode(){$('#scene').innerHTML='<div class="code-slots">☀ 🐍 👁 🪲<br>🔒</div>';$('#challenge').innerHTML='<p class="question">Enter the hieroglyph code in order.</p><div class="answers">'+['👁','☀','🪲','🐍'].map(x=>`<button class="answer">${x}</button>`).join('')+'</div>';let input=[];$$('.answer').forEach(b=>b.onclick=()=>{input.push(b.textContent);toast(input.join(' '));const goal=['☀','🐍','👁','🪲'];if(input.some((v,i)=>v!==goal[i])){input=[];beep(false);toast('THE CODE RESET!')}else if(input.length===4){beep();win()}})}
function win(){const idx=['desert','tomb','treasure'].indexOf(state.game);localStorage.egyptUnlocked=Math.max(+localStorage.egyptUnlocked||0,idx+1);const last=state.game==='treasure';$('#modal').className='reward-modal';$('#modalBody').innerHTML=`<div class="reward-ceremony"><div class="reward-beam"></div><div class="reward-burst">${Array.from({length:16},(_,i)=>`<i style="--i:${i}"></i>`).join('')}</div><div class="reward-halo"><span></span><canvas id="winScarab"></canvas></div><small>GOLDEN SCARAB ${String(idx+1).padStart(2,'0')}</small><h2>${last?'THE LOST TREASURE<br>HAS BEEN FOUND!':state.game==='desert'?'PYRAMID FOUND!':'YOU ESCAPED THE TOMB!'}</h2><p>${last?'The final seal is broken. You are a Master Explorer of Egypt.':`The ${['Emerald','Ruby','Amethyst'][idx]} Scarab has joined your expedition.`}</p><button class="reward-continue" onclick="closeWin()"><span>${last?'VIEW EXPEDITION':'CONTINUE JOURNEY'}</span><b>→</b></button></div>`;$('#modal').showModal();const c=$('#winScarab');c.dataset.reward=idx;if(window.rewardAtlas)drawReward(c,idx,false);beep(true)}
window.closeWin=()=>{$('#modal').close();goHome()};window.dismissMasterScroll=()=>$('.master-scroll').classList.add('dismissed');function goHome(){const modal=$('#modal');if(modal.open)modal.close();state.game=null;$('#game').classList.remove('active');$('#home').classList.add('active');$('.home-nav').hidden=false;window.scrollTo(0,0);playBackground('home');renderProgress()}
$$('.game-card').forEach(c=>c.onclick=()=>openGame(c.dataset.game));$('#backBtn').onclick=goHome;$('#soundBtn').onclick=toggleAudio;$('#resetBtn').onclick=()=>{localStorage.egyptUnlocked=0;$('.master-scroll').classList.remove('dismissed');renderProgress();toast('Expedition reset')};$('#helpBtn').onclick=()=>{$('#modalBody').innerHTML='<h2>HOW TO PLAY</h2><p>Complete six English challenges in each location. Every adventure earns one Golden Scarab and unlocks the next chapter.</p><p>Collect all three scarabs to open the Pharaoh’s treasure.</p>';$('#modal').showModal()};$('#modal .close').onclick=()=>$('#modal').close();renderProgress();loadAtlas();
